name: Keploy API Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  keploy-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./CRUDify/backend

      - name: Download and install Keploy CLI
        run: |
          curl -LO https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64.tar.gz
          tar -xzf keploy-linux-amd64.tar.gz
          sudo mv keploy /usr/local/bin/
        shell: bash

      - name: Run Keploy API tests
        run: keploy test
        working-directory: ./CRUDify/backend

- name: Install Keploy CLI
  run: |
    curl --silent -L https://keploy.io/ent/install.sh | bash


- name: Run Keploy Test Suite
  run: |
    export KEPLOY_API_KEY={KEPLOY_API_KEY}== && keploy test-suite --app=6e75baf8-6881-4189-af8f-6c8b228ab22c --base-path http://localhost:5000/api --cloud

